### PR TITLE
Changed server site json,

### PR DESCRIPTION
**Pull request by daktak**
use https://github.com/daktak/zackwatch_android for battery
added vibrate for people
added example service side scripts

### CODE REVIEW

**Comment by Zwater** [comment]
Line 9 of checkmac.sh may or may not work. I ran into an issue when I first started this where I was using Nmap to run a ping scan of every host on the network, but I found out that Apple devices stop responding to pings almost immediately upon locking, android devices do too after about 10 minutes. That's why I had to use DHCP. The ARP method may work better, but would require all the devices IPs to be static'd and known. This isn't a problem really but it might break an otherwise seamless implementation by having your family/roomates/whoever change something on their devices in order for you to see weather they're home. This isint a problem if you just give them DHCP reservations, but it's an extra step

**Comment by daktak** [comment]
I've made some updates, it seems my router dumpleases isn't always consistent, so I check arp first,
https://github.com/daktak/zackwatch-public/blob/master/server-side/checkmac.sh
Also set up a script on a remote server to push a status into a file, and the main script will include, yet omit if server is unreachable.
https://github.com/daktak/zackwatch-public/blob/master/server-side/updateppl.sh

**Comment by daktak** [comment]
Side note: apk available here https://github.com/daktak/zackwatch_android/releases/download/v0.1/org.zackwatch.apk

**Comment by Zwater** [comment]
Are you getting the same bug I am where all the tuples for the temperature,
with the exception of the conditions, appear to be empty? Also the people
layer dosen't get updates. The statuses make it to setppl() but the
indicators don't get lit up. I only had enough time to pick through your
changes for a couple minutes yesterday. I get a feeling it's just something
I'm forgetting to set in app.js but I haven't had enough time lately to
look into it. I've set the API key and people server, as well as changed
useDefaultLocation to false. This happens with my phone as well as in the
emulator

**Comment by Zwater** [comment]
Also, if you plan on contributing often, I think I can add your public key to the list of people who can push to this repo, either that or set it up to automatically accept pull requests.

**Comment by daktak** [comment]
Out of interest how does defaultloc =true look? I don't have these issues , I'm on a PTS fw ver 3.12. I have metric true, default loc only.
PPL_server is set to http://yoursever/file.json?

**Comment by daktak** [comment]
You get the same on cloudpebble?
Yeah I'm sure I'll be making an update at some point :-)

**Pull request merged**
